//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 03:34:06 PM MESZ 
//


package org.example.aufgabe4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.aufgabe3d package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Collection_QNAME = new QName("http://www.example.org/Aufgabe3d", "collection");
    private final static QName _Date_QNAME = new QName("http://www.example.org/Aufgabe3d", "date");
    private final static QName _Rezept_QNAME = new QName("http://www.example.org/Aufgabe3d", "rezept");
    private final static QName _Brennwert_QNAME = new QName("http://www.example.org/Aufgabe3d", "brennwert");
    private final static QName _Text_QNAME = new QName("http://www.example.org/Aufgabe3d", "text");
    private final static QName _Autor_QNAME = new QName("http://www.example.org/Aufgabe3d", "autor");
    private final static QName _Preparation_QNAME = new QName("http://www.example.org/Aufgabe3d", "preparation");
    private final static QName _Schwierigkeitsgrad_QNAME = new QName("http://www.example.org/Aufgabe3d", "schwierigkeitsgrad");
    private final static QName _RezeptId_QNAME = new QName("http://www.example.org/Aufgabe3d", "rezept-id");
    private final static QName _Ingrediens_QNAME = new QName("http://www.example.org/Aufgabe3d", "ingrediens");
    private final static QName _Arbeitszeit_QNAME = new QName("http://www.example.org/Aufgabe3d", "arbeitszeit");
    private final static QName _Ingredient_QNAME = new QName("http://www.example.org/Aufgabe3d", "ingredient");
    private final static QName _Comment_QNAME = new QName("http://www.example.org/Aufgabe3d", "comment");
    private final static QName _Step_QNAME = new QName("http://www.example.org/Aufgabe3d", "step");
    private final static QName _Comments_QNAME = new QName("http://www.example.org/Aufgabe3d", "comments");
    private final static QName _Picture_QNAME = new QName("http://www.example.org/Aufgabe3d", "picture");
    private final static QName _Title_QNAME = new QName("http://www.example.org/Aufgabe3d", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.aufgabe3d
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PictureType }
     * 
     */
    public PictureType createPictureType() {
        return new PictureType();
    }

    /**
     * Create an instance of {@link PreparationType }
     * 
     */
    public PreparationType createPreparationType() {
        return new PreparationType();
    }

    /**
     * Create an instance of {@link CollectionType }
     * 
     */
    public CollectionType createCollectionType() {
        return new CollectionType();
    }

    /**
     * Create an instance of {@link IngredientType }
     * 
     */
    public IngredientType createIngredientType() {
        return new IngredientType();
    }

    /**
     * Create an instance of {@link CommentsType }
     * 
     */
    public CommentsType createCommentsType() {
        return new CommentsType();
    }

    /**
     * Create an instance of {@link RezeptType }
     * 
     */
    public RezeptType createRezeptType() {
        return new RezeptType();
    }

    /**
     * Create an instance of {@link IngrediensType }
     * 
     */
    public IngrediensType createIngrediensType() {
        return new IngrediensType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "collection")
    public JAXBElement<CollectionType> createCollection(CollectionType value) {
        return new JAXBElement<CollectionType>(_Collection_QNAME, CollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "date")
    public JAXBElement<XMLGregorianCalendar> createDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Date_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RezeptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "rezept")
    public JAXBElement<RezeptType> createRezept(RezeptType value) {
        return new JAXBElement<RezeptType>(_Rezept_QNAME, RezeptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "brennwert")
    public JAXBElement<String> createBrennwert(String value) {
        return new JAXBElement<String>(_Brennwert_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "autor")
    public JAXBElement<String> createAutor(String value) {
        return new JAXBElement<String>(_Autor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreparationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "preparation")
    public JAXBElement<PreparationType> createPreparation(PreparationType value) {
        return new JAXBElement<PreparationType>(_Preparation_QNAME, PreparationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "schwierigkeitsgrad")
    public JAXBElement<String> createSchwierigkeitsgrad(String value) {
        return new JAXBElement<String>(_Schwierigkeitsgrad_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "rezept-id")
    public JAXBElement<Integer> createRezeptId(Integer value) {
        return new JAXBElement<Integer>(_RezeptId_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngrediensType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "ingrediens")
    public JAXBElement<IngrediensType> createIngrediens(IngrediensType value) {
        return new JAXBElement<IngrediensType>(_Ingrediens_QNAME, IngrediensType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "arbeitszeit")
    public JAXBElement<String> createArbeitszeit(String value) {
        return new JAXBElement<String>(_Arbeitszeit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngredientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "ingredient")
    public JAXBElement<IngredientType> createIngredient(IngredientType value) {
        return new JAXBElement<IngredientType>(_Ingredient_QNAME, IngredientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "comment")
    public JAXBElement<CommentType> createComment(CommentType value) {
        return new JAXBElement<CommentType>(_Comment_QNAME, CommentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "step")
    public JAXBElement<String> createStep(String value) {
        return new JAXBElement<String>(_Step_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "comments")
    public JAXBElement<CommentsType> createComments(CommentsType value) {
        return new JAXBElement<CommentsType>(_Comments_QNAME, CommentsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PictureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "picture")
    public JAXBElement<PictureType> createPicture(PictureType value) {
        return new JAXBElement<PictureType>(_Picture_QNAME, PictureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Aufgabe3d", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

}
