//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.10 at 03:34:06 PM MESZ 
//


package org.example.aufgabe4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for preparation_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="preparation_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/Aufgabe3d}arbeitszeit"/>
 *         &lt;element ref="{http://www.example.org/Aufgabe3d}schwierigkeitsgrad"/>
 *         &lt;element ref="{http://www.example.org/Aufgabe3d}brennwert"/>
 *         &lt;element ref="{http://www.example.org/Aufgabe3d}step" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "preparation_type", propOrder = {
    "arbeitszeit",
    "schwierigkeitsgrad",
    "brennwert",
    "step"
})
public class PreparationType {

    @XmlElement(required = true)
    protected String arbeitszeit;
    @XmlElement(required = true)
    protected String schwierigkeitsgrad;
    @XmlElement(required = true)
    protected String brennwert;
    @XmlElement(required = true)
    protected List<String> step;

    /**
     * Gets the value of the arbeitszeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArbeitszeit() {
        return arbeitszeit;
    }

    /**
     * Sets the value of the arbeitszeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArbeitszeit(String value) {
        this.arbeitszeit = value;
    }

    /**
     * Gets the value of the schwierigkeitsgrad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchwierigkeitsgrad() {
        return schwierigkeitsgrad;
    }

    /**
     * Sets the value of the schwierigkeitsgrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchwierigkeitsgrad(String value) {
        this.schwierigkeitsgrad = value;
    }

    /**
     * Gets the value of the brennwert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrennwert() {
        return brennwert;
    }

    /**
     * Sets the value of the brennwert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrennwert(String value) {
        this.brennwert = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the step property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStep() {
        if (step == null) {
            step = new ArrayList<String>();
        }
        return this.step;
    }

}
